---
proxy-providers:
  Gaming:
    type: http
    url: "https://raw.githubusercontent.com/clashz3ro/Pisah_traffic/main/gaming.yaml"
    path: "./proxy_provider/gaming.yaml"
    health-check:
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: 120
  Sosmed:
    type: http
    url: "https://raw.githubusercontent.com/clashz3ro/Pisah_traffic/main/sosmed.yaml"
    path: "./proxy_provider/sosmed.yaml"
    health-check:
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: 120
  Streaming:
    type: http
    url: "http://fool.azurewebsites.net/get?limit=10&format=clash&cc=SG,ID&cdn=104.18.2.2&network=ws&arg=xudp,key:value&mode=cdn&pass=qk4ndl7g"
    path: "./proxy_provider/streaming.yaml"
    health-check:
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: 120
  Umum:
    type: http
    url: "https://raw.githubusercontent.com/clashz3ro/Pisah_traffic/main/umum.yaml"
    path: "./proxy_provider/umum.yaml"
    health-check:
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: 120
  trafficIndo:
    type: http
    url: "https://raw.githubusercontent.com/clashz3ro/Pisah_traffic/main/trafficIndo.yaml"
    path: "./proxy_provider/trafficIndo.yaml"
    health-check:
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: 120
proxy-groups:
- name: Gaming
  type: select
  disable-udp: false
  use:
  - Gaming
- name: Sosmed
  type: load-balance
  strategy: round-robin
  disable-udp: false
  use:
  - Sosmed
  url: http://www.gstatic.com/generate_204
  interval: '300'
- name: Streaming
  type: load-balance
  strategy: round-robin
  disable-udp: false
  use:
  - Streaming
  url: http://www.gstatic.com/generate_204
  interval: '300'
- name: trafficIndo
  type: load-balance
  strategy: round-robin
  disable-udp: false
  use:
  - trafficIndo
  url: http://www.gstatic.com/generate_204
  interval: '300'
- name: Umum
  type: load-balance
  strategy: round-robin
  disable-udp: false
  use:
  - Umum
  url: http://www.gstatic.com/generate_204
  interval: '300'
redir-port: 7892
port: 7890
socks-port: 7891
mixed-port: 7893
mode: script
log-level: silent
allow-lan: true
external-controller: 0.0.0.0:9090
secret: ''
bind-address: "*"
external-ui: "/usr/share/openclash/ui"
dns:
  enable: true
  ipv6: false
  enhanced-mode: fake-ip
  listen: 0.0.0.0:7874
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
  - "*.lan"
  - "*.localdomain"
  - "*.example"
  - "*.invalid"
  - "*.localhost"
  - "*.test"
  - "*.local"
  - "*.home.arpa"
  - time.*.com
  - time.*.gov
  - time.*.edu.cn
  - time.*.apple.com
  - time1.*.com
  - time2.*.com
  - time3.*.com
  - time4.*.com
  - time5.*.com
  - time6.*.com
  - time7.*.com
  - ntp.*.com
  - ntp1.*.com
  - ntp2.*.com
  - ntp3.*.com
  - ntp4.*.com
  - ntp5.*.com
  - ntp6.*.com
  - ntp7.*.com
  - "*.time.edu.cn"
  - "*.ntp.org.cn"
  - "+.pool.ntp.org"
  - time1.cloud.tencent.com
  - music.163.com
  - "*.music.163.com"
  - "*.126.net"
  - musicapi.taihe.com
  - music.taihe.com
  - songsearch.kugou.com
  - trackercdn.kugou.com
  - "*.kuwo.cn"
  - api-jooxtt.sanook.com
  - api.joox.com
  - joox.com
  - y.qq.com
  - "*.y.qq.com"
  - streamoc.music.tc.qq.com
  - mobileoc.music.tc.qq.com
  - isure.stream.qqmusic.qq.com
  - dl.stream.qqmusic.qq.com
  - aqqmusic.tc.qq.com
  - amobile.music.tc.qq.com
  - "*.xiami.com"
  - "*.music.migu.cn"
  - music.migu.cn
  - "+.msftconnecttest.com"
  - "+.msftncsi.com"
  - msftconnecttest.com
  - msftncsi.com
  - localhost.ptlogin2.qq.com
  - localhost.sec.qq.com
  - "+.srv.nintendo.net"
  - "+.stun.playstation.net"
  - xbox.*.microsoft.com
  - xnotify.xboxlive.com
  - "+.battlenet.com.cn"
  - "+.wotgame.cn"
  - "+.wggames.cn"
  - "+.wowsgame.cn"
  - "+.wargaming.net"
  - proxy.golang.org
  - stun.*.*
  - stun.*.*.*
  - "+.stun.*.*"
  - "+.stun.*.*.*"
  - "+.stun.*.*.*.*"
  - heartbeat.belkin.com
  - "*.linksys.com"
  - "*.linksyssmartwifi.com"
  - "*.router.asus.com"
  - mesu.apple.com
  - swscan.apple.com
  - swquery.apple.com
  - swdownload.apple.com
  - swcdn.apple.com
  - swdist.apple.com
  - lens.l.google.com
  - stun.l.google.com
  - "+.nflxvideo.net"
  - "*.square-enix.com"
  - "*.finalfantasyxiv.com"
  - "*.ffxiv.com"
  - "*.mcdn.bilivideo.cn"
  - "+.media.dssott.com"
  - time-ios.apple.com
  - "*.n.n.srv.nintendo.net"
  - xbox.*.*.microsoft.com
  - "*.*.xboxlive.com"
  - "+.stun.*.*.*.*.*"
  - "*.ff14.sdo.com"
  - ff.dorado.sdo.com
  - shark007.net
  default-nameserver:
  - 127.0.0.1:5054
  - 127.0.0.1:5053
  - 10.0.8.1
  - 192.168.11.1
  - 192.168.10.1
  - 8.8.8.8
  - 1.1.1.1
  - 192.168.8.1
  fallback-filter:
    geoip: true
    geoip-code: ID
    ipcidr:
    - 0.0.0.0/8
    - 10.0.0.0/8
    - 100.64.0.0/10
    - 127.0.0.0/8
    - 169.254.0.0/16
    - 172.16.0.0/12
    - 192.0.0.0/24
    - 192.0.2.0/24
    - 192.88.99.0/24
    - 192.168.0.0/16
    - 198.18.0.0/15
    - 198.51.100.0/24
    - 203.0.113.0/24
    - 224.0.0.0/4
    - 240.0.0.0/4
    - 255.255.255.255/32
    domain:
    - "+.google.com"
    - "+.facebook.com"
    - "+.youtube.com"
    - "+.githubusercontent.com"
    - "+.googlevideo.com"
    - "+.msftconnecttest.com"
    - "+.msftncsi.com"
    - msftconnecttest.com
    - msftncsi.com
  nameserver:
  - dhcp://"eth2"
  - 192.168.8.1
  - 127.0.0.1:5054
  - 8.8.8.8
  fallback:
  - 127.0.0.1:5054
  - 1.1.1.1
profile:
  store-selected: true
  store-fakeip: true
  store-fake-ip: true
rules:
- DST-PORT,7895,REJECT
- DST-PORT,7892,REJECT
- IP-CIDR,198.18.0.1/16,REJECT,no-resolve
- PROCESS-NAME,v2ray,DIRECT
- PROCESS-NAME,xray,DIRECT
- PROCESS-NAME,naive,DIRECT
- PROCESS-NAME,trojan,DIRECT
- PROCESS-NAME,trojan-go,DIRECT
- PROCESS-NAME,ss-local,DIRECT
- PROCESS-NAME,privoxy,DIRECT
- PROCESS-NAME,leaf,DIRECT
- PROCESS-NAME,v2ray.exe,DIRECT
- PROCESS-NAME,xray.exe,DIRECT
- PROCESS-NAME,naive.exe,DIRECT
- PROCESS-NAME,trojan.exe,DIRECT
- PROCESS-NAME,trojan-go.exe,DIRECT
- PROCESS-NAME,ss-local.exe,DIRECT
- PROCESS-NAME,privoxy.exe,DIRECT
- RULE-SET,rule_BlockAds,REJECT
- RULE-SET,rule_reject,REJECT
- RULE-SET,rule_basicads,REJECT
- RULE-SET,rule_privacy,REJECT
- RULE-SET,rule_lancidr,DIRECT,no-resolve
- RULE-SET,rule_Speedtest,Umum
- RULE-SET,rule_Streaming,Streaming
- RULE-SET,rule_disneyplus,trafficIndo
- RULE-SET,rule_hbo,Streaming
- RULE-SET,rule_iqiyi,Streaming
- RULE-SET,rule_netflix,trafficIndo
- RULE-SET,rule_primevideo,Streaming
- RULE-SET,rule_twitch,Streaming
- RULE-SET,rule_Youtube,Streaming
- RULE-SET,rule_Sosmed,Sosmed
- RULE-SET,rule_line,Sosmed
- RULE-SET,rule_metaverse,Sosmed
- RULE-SET,rule_tiktok,Sosmed
- RULE-SET,rule_twitter,Sosmed
- RULE-SET,rule_telegram,Sosmed
- RULE-SET,rule_telegramcidr,Sosmed
- RULE-SET,rule_Indo,trafficIndo
- RULE-SET,rule_videoconferences,Streaming
- RULE-SET,rule_playstore,Umum
- RULE-SET,rule_Gaming,Gaming
- RULE-SET,rule_discord,Gaming
- RULE-SET,rule_games,Gaming
- RULE-SET,rule_portgames,Gaming
- RULE-SET,rule_umum,Umum
- MATCH,GLOBAL
tun:
  enable: true
  stack: system
  auto-route: false
  auto-detect-interface: false
  dns-hijack:
  - tcp://any:53
tproxy-port: 7895
rule-providers:
  rule_Direct:
    type: file
    behavior: classical
    path: "./rule_provider/rule_direct.yaml"
  rule_umum:
    type: http
    behavior: classical
    path: "./rule_provider/rule_umum.yaml"
    url: https://cdn.jsdelivr.net/gh/malikshi/open_clash@main/rule_provider/rule_umum.yaml
    interval: 86400
  rule_portgames:
    type: http
    behavior: classical
    path: "./rule_provider/rule_portgames.yaml"
    url: https://cdn.jsdelivr.net/gh/malikshi/open_clash@main/rule_provider/rule_portgames.yaml
    interval: 86400
  rule_videoconferences:
    type: http
    behavior: classical
    path: "./rule_provider/rule_videoconferences.yaml"
    url: https://cdn.jsdelivr.net/gh/malikshi/open_clash@main/rule_provider/rule_videoconferences.yaml
    interval: 86400
  rule_Indo:
    type: http
    behavior: classical
    path: "./rule_provider/rule_Indo.yaml"
    url: https://cdn.jsdelivr.net/gh/malikshi/open_clash@main/rule_provider/rule_Indo.yaml
    interval: 86400
  rule_Sosmed:
    type: http
    behavior: classical
    path: "./rule_provider/rule_sosmed.yaml"
    url: https://cdn.jsdelivr.net/gh/malikshi/open_clash@main/rule_provider/rule_sosmed.yaml
    interval: 86400
  rule_Streaming:
    type: http
    behavior: classical
    path: "./rule_provider/rule_streaming.yaml"
    url: https://cdn.jsdelivr.net/gh/malikshi/open_clash@main/rule_provider/rule_streaming.yaml
    interval: 86400
  rule_Gaming:
    type: http
    behavior: classical
    path: "./rule_provider/rule_gaming.yaml"
    url: https://cdn.jsdelivr.net/gh/malikshi/open_clash@main/rule_provider/rule_gaming.yaml
    interval: 86400
  rule_Speedtest:
    type: http
    behavior: domain
    url: https://rules.kr328.app/speedtest.yaml
    path: "./rule_provider/rule_speedtest.yaml"
    interval: 86400
  rule_discord:
    type: http
    behavior: domain
    url: https://rules.kr328.app/discord.yaml
    path: "./rule_provider/rule_discord.yaml"
    interval: 86400
  rule_BlockAds:
    type: http
    behavior: classical
    path: "./rule_provider/rule_BlockAds.yaml"
    url: https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Advertising/Advertising_Classical.yaml
    interval: 86400
  rule_reject:
    type: http
    behavior: domain
    url: https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/reject.txt
    path: "./rule_provider/rule_reject.yaml"
    interval: 86400
  rule_privacy:
    type: http
    behavior: classical
    url: https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Privacy/Privacy_Classical.yaml
    path: "./rule_provider/rule_privacy.yaml"
    interval: 86400
  rule_basicads:
    type: http
    behavior: classical
    url: https://cdn.jsdelivr.net/gh/malikshi/open_clash@main/rule_provider/rule_basicads.yaml
    path: "./rule_provider/rule_basicads.yaml"
    interval: 86400
  rule_nsfw:
    type: http
    behavior: classical
    url: https://cdn.jsdelivr.net/gh/malikshi/open_clash@main/rule_provider/rule_nsfw.yaml
    path: "./rule_provider/rule_nsfw.yaml"
    interval: 86400
  rule_lancidr:
    type: http
    behavior: ipcidr
    url: https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/lancidr.txt
    path: "./rule_provider/rule_lancidr.yaml"
    interval: 86400
  rule_telegramcidr:
    type: http
    behavior: ipcidr
    url: https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/telegramcidr.txt
    path: "./rule_provider/rule_telegramcidr.yaml"
    interval: 86400
  rule_telegram:
    type: http
    behavior: domain
    url: https://rules.kr328.app/telegram.yaml
    path: "./rule_provider/rule_telegram.yaml"
    interval: 86400
  rule_disneyplus:
    type: http
    behavior: domain
    url: https://rules.kr328.app/disney.yaml
    path: "./rule_provider/rule_disneyplus.yaml"
    interval: 86400
  rule_games:
    type: http
    behavior: domain
    url: https://rules.kr328.app/category-games.yaml
    path: "./rule_provider/rule_games.yaml"
    interval: 86400
  rule_hbo:
    type: http
    behavior: domain
    url: https://rules.kr328.app/hbo.yaml
    path: "./rule_provider/rule_hbo.yaml"
    interval: 86400
  rule_iqiyi:
    type: http
    behavior: domain
    url: https://rules.kr328.app/iqiyi.yaml
    path: "./rule_provider/rule_iqiyi.yaml"
    interval: 86400
  rule_line:
    type: http
    behavior: domain
    url: https://rules.kr328.app/line.yaml
    path: "./rule_provider/rule_line.yaml"
    interval: 86400
  rule_metaverse:
    type: http
    behavior: domain
    url: https://rules.kr328.app/facebook.yaml
    path: "./rule_provider/rule_metaverse.yaml"
    interval: 86400
  rule_netflix:
    type: http
    behavior: domain
    url: https://rules.kr328.app/netflix.yaml
    path: "./rule_provider/rule_netflix.yaml"
    interval: 86400
  rule_primevideo:
    type: http
    behavior: domain
    url: https://rules.kr328.app/primevideo.yaml
    path: "./rule_provider/rule_primevideo.yaml"
    interval: 86400
  rule_playstore:
    type: http
    behavior: domain
    url: https://cdn.jsdelivr.net/gh/malikshi/open_clash@main/rule_provider/rule_playstore.yaml
    path: "./rule_provider/rule_playstore.yaml"
    interval: 86400
  rule_tiktok:
    type: http
    behavior: domain
    url: https://rules.kr328.app/tiktok.yaml
    path: "./rule_provider/rule_tiktok.yaml"
    interval: 86400
  rule_twitch:
    type: http
    behavior: domain
    url: https://rules.kr328.app/twitch.yaml
    path: "./rule_provider/rule_twitch.yaml"
    interval: 86400
  rule_twitter:
    type: http
    behavior: domain
    url: https://rules.kr328.app/twitter.yaml
    path: "./rule_provider/rule_twitter.yaml"
    interval: 86400
  rule_Youtube:
    type: http
    behavior: domain
    url: https://rules.kr328.app/youtube.yaml
    path: "./rule_provider/rule_Youtube.yaml"
    interval: 86400
ipv6: false
